stages:
  - build
  - push

variables:
  IMAGE_NAME: "registry.gitlab.com/hadil9775947/backend"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest # Push immediately after build
  only:
    - main

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker pull $IMAGE_NAME:latest # Pull the image for validation or further use
    - docker push $IMAGE_NAME:latest # Push again (optional, if necessary)
  needs:
    - build_image
  only:
    - main
