image: docker:latest

services:
  - docker:dind

stages:
  - build


before_script:
  # Login to GitLab Container Registry
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build_image:
  stage: build
  script:
    # Build the Docker image and tag it
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    # Push the image to the GitLab Container Registry
    - docker push $CI_REGISTRY_IMAGE:latest
