stages:
  - build
  - push

variables:
  IMAGE_NAME: "registry.gitlab.com/hadil9775947/backend"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - echo "Checking for Dockerfile and project files:"
    - ls -la
    - echo "Building the Docker image:"
    - docker build --progress=plain -t $IMAGE_NAME:latest .
    - echo "Listing Docker images after build:"
    - docker images

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - echo "Listing Docker images before push:"
    - docker images
    - docker push $IMAGE_NAME:latest
  needs:
    - build_image
