image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push


before_script:
  # Authenticate to the GitLab Container Registry
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build_image:
  stage: build
  script:
    # Build the Docker image and tag it
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    # Ensure the image is available for the next stage
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest

push_image:
  stage: push
  script:
    # Push the previously built image to the registry
    - docker push $CI_REGISTRY_IMAGE:latest
