stages:
  - build
  - push

variables:
  IMAGE_NAME: "registry.gitlab.com/hadil9775947/backend"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:latest .

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $IMAGE_NAME:latest
  needs:
    - build_image
