image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

before_script:
  # Authenticate to the GitLab Container Registry
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build_image:
  stage: build
  script:
    # Build and tag the Docker image
    - docker build -t $CI_REGISTRY_IMAGE:latest .

push_image:
  stage: push
  script:
    # Push the Docker image to the registry
    - docker push $CI_REGISTRY_IMAGE:latest
